version: '3.5'

services:
  # keycloak db
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend

  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      #      KEYCLOAK_LOGLEVEL: DEBUG
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/test-realm.json
    volumes:
      - ./test-realm.json:/tmp/test-realm.json
    ports:
      - 9990:8080
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: bridge
